name = "logical-mechanism/drep-contract"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "GPL-3.0-or-later"
description = "Aiken contracts for project 'logical-mechanism/drep-contract'"

[repository]
user = "logical-mechanism"
project = "drep-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.0"
source = "github"

[config]
